import { v } from "convex/values";

/** Shared measurement field validators — single source of truth for measurements.ts, import.ts, and schema.ts */
export const measurementFields = {
  date: v.number(),
  weight: v.optional(v.number()),
  waistCirc: v.optional(v.number()),
  neckCirc: v.optional(v.number()),
  hipCirc: v.optional(v.number()),
  height: v.optional(v.number()),
  skinfoldChest: v.optional(v.number()),
  skinfoldAxilla: v.optional(v.number()),
  skinfoldTricep: v.optional(v.number()),
  skinfoldSubscapular: v.optional(v.number()),
  skinfoldAbdominal: v.optional(v.number()),
  skinfoldSuprailiac: v.optional(v.number()),
  skinfoldThigh: v.optional(v.number()),
  skinfoldBicep: v.optional(v.number()),
  upperArmCirc: v.optional(v.number()),
  lowerArmCirc: v.optional(v.number()),
  thighCirc: v.optional(v.number()),
  calfCirc: v.optional(v.number()),
  chestCirc: v.optional(v.number()),
  shoulderCirc: v.optional(v.number()),
  time5k: v.optional(v.number()),
  time1k: v.optional(v.number()),
  lMinO2: v.optional(v.number()),
  sKmAt129Bpm: v.optional(v.number()),
  vo2max: v.optional(v.number()),
};

/** Optional version of all measurement fields (for update mutations) */
export const optionalMeasurementFields = {
  date: v.optional(v.number()),
  weight: v.optional(v.number()),
  waistCirc: v.optional(v.number()),
  neckCirc: v.optional(v.number()),
  hipCirc: v.optional(v.number()),
  height: v.optional(v.number()),
  skinfoldChest: v.optional(v.number()),
  skinfoldAxilla: v.optional(v.number()),
  skinfoldTricep: v.optional(v.number()),
  skinfoldSubscapular: v.optional(v.number()),
  skinfoldAbdominal: v.optional(v.number()),
  skinfoldSuprailiac: v.optional(v.number()),
  skinfoldThigh: v.optional(v.number()),
  skinfoldBicep: v.optional(v.number()),
  upperArmCirc: v.optional(v.number()),
  lowerArmCirc: v.optional(v.number()),
  thighCirc: v.optional(v.number()),
  calfCirc: v.optional(v.number()),
  chestCirc: v.optional(v.number()),
  shoulderCirc: v.optional(v.number()),
  time5k: v.optional(v.number()),
  time1k: v.optional(v.number()),
  lMinO2: v.optional(v.number()),
  sKmAt129Bpm: v.optional(v.number()),
  vo2max: v.optional(v.number()),
};
